// Generated by gencpp from file line_lbd/My_image.msg
// DO NOT EDIT!


#ifndef LINE_LBD_MESSAGE_MY_IMAGE_H
#define LINE_LBD_MESSAGE_MY_IMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace line_lbd
{
template <class ContainerAllocator>
struct My_image_
{
  typedef My_image_<ContainerAllocator> Type;

  My_image_()
    : id()
    , image_now()  {
    }
  My_image_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , image_now(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_now_type;
  _image_now_type image_now;





  typedef boost::shared_ptr< ::line_lbd::My_image_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::line_lbd::My_image_<ContainerAllocator> const> ConstPtr;

}; // struct My_image_

typedef ::line_lbd::My_image_<std::allocator<void> > My_image;

typedef boost::shared_ptr< ::line_lbd::My_image > My_imagePtr;
typedef boost::shared_ptr< ::line_lbd::My_image const> My_imageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::line_lbd::My_image_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::line_lbd::My_image_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::line_lbd::My_image_<ContainerAllocator1> & lhs, const ::line_lbd::My_image_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.image_now == rhs.image_now;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::line_lbd::My_image_<ContainerAllocator1> & lhs, const ::line_lbd::My_image_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace line_lbd

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::line_lbd::My_image_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_lbd::My_image_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::line_lbd::My_image_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::line_lbd::My_image_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_lbd::My_image_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_lbd::My_image_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::line_lbd::My_image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1c0f8ba6177c2fb6b3fcb7d6bfbd0e0";
  }

  static const char* value(const ::line_lbd::My_image_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1c0f8ba6177c2fbULL;
  static const uint64_t static_value2 = 0x6b3fcb7d6bfbd0e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::line_lbd::My_image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "line_lbd/My_image";
  }

  static const char* value(const ::line_lbd::My_image_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::line_lbd::My_image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n"
"sensor_msgs/Image image_now\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::line_lbd::My_image_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::line_lbd::My_image_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.image_now);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct My_image_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::line_lbd::My_image_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::line_lbd::My_image_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "image_now: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image_now);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINE_LBD_MESSAGE_MY_IMAGE_H
