// Generated by gencpp from file line_lbd/my_mat.msg
// DO NOT EDIT!


#ifndef LINE_LBD_MESSAGE_MY_MAT_H
#define LINE_LBD_MESSAGE_MY_MAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace line_lbd
{
template <class ContainerAllocator>
struct my_mat_
{
  typedef my_mat_<ContainerAllocator> Type;

  my_mat_()
    : pose()  {
    }
  my_mat_(const ContainerAllocator& _alloc)
    : pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::line_lbd::my_mat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::line_lbd::my_mat_<ContainerAllocator> const> ConstPtr;

}; // struct my_mat_

typedef ::line_lbd::my_mat_<std::allocator<void> > my_mat;

typedef boost::shared_ptr< ::line_lbd::my_mat > my_matPtr;
typedef boost::shared_ptr< ::line_lbd::my_mat const> my_matConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::line_lbd::my_mat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::line_lbd::my_mat_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::line_lbd::my_mat_<ContainerAllocator1> & lhs, const ::line_lbd::my_mat_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::line_lbd::my_mat_<ContainerAllocator1> & lhs, const ::line_lbd::my_mat_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace line_lbd

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::line_lbd::my_mat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_lbd::my_mat_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::line_lbd::my_mat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::line_lbd::my_mat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_lbd::my_mat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_lbd::my_mat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::line_lbd::my_mat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76249fb45cba333e6a82c7f91cfe1879";
  }

  static const char* value(const ::line_lbd::my_mat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76249fb45cba333eULL;
  static const uint64_t static_value2 = 0x6a82c7f91cfe1879ULL;
};

template<class ContainerAllocator>
struct DataType< ::line_lbd::my_mat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "line_lbd/my_mat";
  }

  static const char* value(const ::line_lbd::my_mat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::line_lbd::my_mat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] pose\n"
"\n"
"\n"
;
  }

  static const char* value(const ::line_lbd::my_mat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::line_lbd::my_mat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_mat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::line_lbd::my_mat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::line_lbd::my_mat_<ContainerAllocator>& v)
  {
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINE_LBD_MESSAGE_MY_MAT_H
