# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from line_lbd/Keyline_vec.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import line_lbd.msg

class Keyline_vec(genpy.Message):
  _md5sum = "66d8e92245e6e28ba0b9fa23e5b92a2d"
  _type = "line_lbd/Keyline_vec"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string id
uint32 length
Keyline[] Keylines
================================================================================
MSG: line_lbd/Keyline
float32 startPointX
float32 startPointY
float32 endPointX
float32 endPointY"""
  __slots__ = ['id','length','Keylines']
  _slot_types = ['string','uint32','line_lbd/Keyline[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,length,Keylines

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Keyline_vec, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = ''
      if self.length is None:
        self.length = 0
      if self.Keylines is None:
        self.Keylines = []
    else:
      self.id = ''
      self.length = 0
      self.Keylines = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.length
      buff.write(_get_struct_I().pack(_x))
      length = len(self.Keylines)
      buff.write(_struct_I.pack(length))
      for val1 in self.Keylines:
        _x = val1
        buff.write(_get_struct_4f().pack(_x.startPointX, _x.startPointY, _x.endPointX, _x.endPointY))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Keylines is None:
        self.Keylines = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.id = str[start:end]
      start = end
      end += 4
      (self.length,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.Keylines = []
      for i in range(0, length):
        val1 = line_lbd.msg.Keyline()
        _x = val1
        start = end
        end += 16
        (_x.startPointX, _x.startPointY, _x.endPointX, _x.endPointY,) = _get_struct_4f().unpack(str[start:end])
        self.Keylines.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.length
      buff.write(_get_struct_I().pack(_x))
      length = len(self.Keylines)
      buff.write(_struct_I.pack(length))
      for val1 in self.Keylines:
        _x = val1
        buff.write(_get_struct_4f().pack(_x.startPointX, _x.startPointY, _x.endPointX, _x.endPointY))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Keylines is None:
        self.Keylines = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.id = str[start:end]
      start = end
      end += 4
      (self.length,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.Keylines = []
      for i in range(0, length):
        val1 = line_lbd.msg.Keyline()
        _x = val1
        start = end
        end += 16
        (_x.startPointX, _x.startPointY, _x.endPointX, _x.endPointY,) = _get_struct_4f().unpack(str[start:end])
        self.Keylines.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
